rootPageId: 1 # Domain/Root page UID from the BE page tree
base: 'http://www.domain.tld/'
baseVariants:
  -
    base: 'http://preview.domain.tld/'
    condition: 'applicationContext == "Development/Server"'
  -
    base: 'http://www.domain.localhost/'
    condition: 'applicationContext == "Development"'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: '0'
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de
    direction: ltr
    flag: de
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=3' # uid = page UID from the BE page tree
  -
    errorCode: '503'
    errorHandler: Page
    errorContentSource: 't3://page?uid=4' # uid = page UID from the BE page tree
routes:
  -
    route: robots.txt
    type: staticText # content: end of line change the URL to the sitemap!
    content: "User-Agent: *\r\nAllow: /\r\nDisallow: /fileadmin/templates\r\nDisallow: /typo3/\r\nDisallow: /t3lib/\r\nDisallow: /typo3conf/\r\nDisallow: /typo3temp/\r\nDisallow: /*?id=*\r\nDisallow: /*?tx_indexedsearch\r\nDisallow: /*?id=*\r\nDisallow: /print/\r\n\r\nSitemap: https://www.domain.tld/sitemap.xml"
  -
    route: sitemap.xml
    type: uri
    source: 't3://page?uid=1&type=1533906435' # uid = Domain/Root page UID from the BE page tree
routeEnhancers:
  NewsPlugin:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/list/{page}'
        _controller: 'News::list'
        _arguments:
          page: '@widget_0/currentPage'
      -
        routePath: '/tag/{tag_name}'
        _controller: 'News::list'
        _arguments:
          tag_name: overwriteDemand/tags
      -
        routePath: '/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
      -
        routePath: '/archive/{year}/{month}'
        _controller: 'News::archive'
    defaultController: 'News::list'
    aspects:
      news_title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      month:
        type: StaticValueMapper
        map:
          january: 1
          february: 2
          march: 3
          april: 4
          may: 5
          june: 6
          july: 7
          august: 8
          september: 9
          october: 10
          november: 11
          december: 12
        localeMap:
          - locale: 'de_.*'
            map:
                januar: 1
                februar: 2
                maerz: 3
                april: 4
                mai: 5
                juni: 6
                juli: 7
                august: 8
                september: 9
                oktober: 10
                november: 11
                dezember: 12
  AddressPlugin:
    type: Extbase
    extension: TtAddress
    plugin: ListView
    routes:
      - routePath: '/{address_slug}'
        _controller: 'Address::show'
        _arguments:
          address_slug: address
    aspects:
      address_slug:
        type: PersistedAliasReplaceMapper
        replaceSource: ' '
        replaceTarget: '-'
        toLower: 1
        tableName: tt_address
        routeFieldName: name
